name: Scheduled Commits

on:
  schedule: 
    - cron: '0 */2 * * *'

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

      # Step 3: Select a random commit message
      - name: Select random commit message
        id: random_message
        run: |
          # Parse the JSON file to extract commit messages
          commit_messages=$(cat commitMessages.json | jq -r '.[]')
          # Convert JSON array to a bash array
          mapfile -t messages <<< "$commit_messages"
          # Pick a random message
          RANDOM_INDEX=$((RANDOM % ${#messages[@]}))
          RANDOM_MESSAGE=${messages[$RANDOM_INDEX]}
          echo "message=$RANDOM_MESSAGE" >> $GITHUB_ENV

      # Step 4: Append date and time to the text file
      - name: Append date and time to file
        run: |
          echo "$(date) - " >> cron-job-info.txt

      # Step 5: Commit the file
      - name: Commit changes
        run: |
          git add cron-job-info.txt
          git commit -m "$message"

      # Step 6: Push the changes
      - name: Push changes
        run: |
          git push
